//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by main.rc
//
#define IDD_INTRODUTION                 101
#define IDD_INSTALL                     102
#define IDD_REMOTE                      103
#define IDD_PID                         104
#define IDD_CALIBRATION                 105
#define IDD_PROFILE                     106
#define IDD_DIALOG1                     107
#define IDD_MAIN                        107
#define IDB_BG                          110
#define IDB_BITMAP2                     111
#define IDB_EXPORT                      111
#define IDB_SAVE_DOWN                   112
#define IDB_SAVE_HOVER                  113
#define IDB_SAVE_NORMAL                 114
#define IDB_CLOSE_DOWN                  115
#define IDB_CLOSE_HOVER                 116
#define IDB_CLOSE_NORMAL                117
#define IDB_MINIMIZE_DOWN               118
#define IDB_MINIMIZE_HOVER              119
#define IDB_MINIMIZE_NORMAL             120
#define IDB_RESET_DOWN                  122
#define IDB_RESET_HOVER                 123
#define IDB_BITMAP4                     124
#define IDB_RESET_NORMAL                124
#define IDB_IMPORT_DOWN                 125
#define IDB_IMPORT_HOVER                126
#define IDB_BITMAP5                     127
#define IDB_IMPORT_NORMAL               127
#define IDB_MENU0_DOWN                  129
#define IDB_MENU0_HOVER                 130
#define IDB_MENU0_NORMAL                131
#define IDB_MENU1_DOWN                  132
#define IDB_MENU1_HOVER                 133
#define IDB_MENU1_NORMAL                134
#define IDB_MENU2_DOWN                  135
#define IDB_MENU2_HOVER                 136
#define IDB_BITMAP9                     137
#define IDB_MENU2_NORMAL                137
#define IDB_MENU3_DOWN                  138
#define IDB_MENU3_HOVER                 139
#define IDB_MENU3_NORMAL                140
#define IDB_MENU4_DOWN                  141
#define IDB_MENU4_HOVER                 142
#define IDB_MENU4_NORMAL                143
#define IDI_ICON1                       144
#define IDB_I_NORMAL                    145
#define IDB_BITMAP3                     146
#define IDB_X_NORMAL                    146
#define IDB_I_DOWN                      147
#define IDB_I_                          148
#define IDB_I_MOUSEOVER                 148
#define IDB_X_DOWN                      149
#define IDB_X_mouseover                 150
#define IDB_RC_BG                       151
#define IDR_GRAPH                       152
#define IDC_BUTTON1                     1001
#define IDC_OD                          1001
#define IDC_BYE                         1001
#define IDC_CLOSE                       1001
#define IDC_BUTTON2                     1002
#define IDC_MINIMIZE                    1002
#define IDC_DRIVER                      1002
#define IDC_RADIO1                      1003
#define IDC_BUTTON3                     1003
#define IDC_IDLE_0                      1003
#define IDC_SAVE                        1003
#define IDC_RADIO2                      1004
#define IDC_SLIDER1                     1004
#define IDC_BUTTON6                     1004
#define IDC_CALIBRATION                 1004
#define IDC_IDLE_1                      1004
#define IDC_RADIO3                      1005
#define IDC_SLIDER2                     1005
#define IDC_BUTTON7                     1005
#define IDC_PROFILE                     1005
#define IDC_IDLE_2                      1005
#define IDC_RADIO4                      1006
#define IDC_SLIDER3                     1006
#define IDC_EDIT1                       1006
#define IDC_RATE_0                      1006
#define IDC_IDLE_3                      1006
#define IDC_RADIO5                      1007
#define IDC_BUTTON4                     1007
#define IDC_EDIT2                       1007
#define IDC_REVERT2                     1007
#define IDC_RATE_1                      1007
#define IDC_IDLE_4                      1007
#define IDC_EDIT3                       1008
#define IDC_TAB1                        1008
#define IDC_RATE_2                      1008
#define IDC_SLIDER5                     1008
#define IDC_EDIT4                       1009
#define IDC_INSTALL                     1009
#define IDC_VERTICAL                    1009
#define IDC_SLIDER4                     1010
#define IDC_EDIT5                       1010
#define IDC_REMOTE                      1010
#define IDC_STABLIZE_0                  1010
#define IDC_BUTTON5                     1011
#define IDC_EDIT6                       1011
#define IDC_PID                         1011
#define IDC_REVERT3                     1011
#define IDC_STABLIZE_1                  1011
#define IDC_EDIT7                       1012
#define IDC_PAGES                       1012
#define IDC_STABLIZE_2                  1012
#define IDC_SLIDER6                     1012
#define IDC_EDIT8                       1013
#define IDC_CHECK1                      1013
#define IDC_EDIT9                       1014
#define IDC_GYRO0                       1014
#define IDC_RATE_D0                     1014
#define IDC_EDIT10                      1015
#define IDC_GYRO1                       1015
#define IDC_RATE_D1                     1015
#define IDC_EDIT11                      1016
#define IDC_RATE_D2                     1016
#define IDC_CAL_T1                      1017
#define IDC_CAL_T2                      1018
#define IDC_RC                          1019
#define IDC_REVERT0                     1020
#define IDC_REVERT1                     1021
#define IDC_RADIO_MATRIX0               1022
#define IDC_RADIO_MATRIX1               1023
#define IDC_TEMP                        1026
#define IDC_ACCEL                       1027
#define IDC_RESET                       1028
#define IDC_IMUSTATE                    1029
#define IDC_REVERT4                     1034
#define IDC_REVERT5                     1035
#define IDC_GYRO2                       1036
#define IDC_MATRIX_0                    1039
#define IDC_MATRIX_1                    1040
#define IDC_GRAPH                       1044
#define IDC_STATIC_T2                   1045
#define ID_REMOTE_40001                 40001
#define ID_REMOTE_40002                 40002
#define ID_MODE1                        40003
#define ID_MODE2                        40004
#define IDC_LOAD                        51001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        153
#define _APS_NEXT_COMMAND_VALUE         40005
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
